server.port=8081

# SQS config — same account as server-v2
app.sqs.region=us-west-2
app.sqs.account-id=449126751631
app.sqs.queue-name-prefix=chatflow-room-

# Number of polling threads — one per room by default
app.consumer.threads=20

# Comma-separated list of server-v2 base URLs to broadcast to
# Part 1: single server
# Part 3: add more entries e.g. http://localhost:8080,http://localhost:8082
# Part 3: Consumer on separate EC2, broadcast to both Server EC2s via private IP
app.broadcast.server-urls=http://172.31.25.72:8080,http://172.31.24.104:8080
